INSERT INTO portfolios (
    title, short_description, full_details, client_name, completion_date, 
    technology_stack, website_url, github_url, status, category, display_order, 
    featured, banner_image, screenshots, slug
) VALUES 
('E-commerce Platform Redesign', 'A modern, high-performance e-commerce platform built with React and Node.js.', 'We completely overhauled the client''s legacy e-commerce system, resulting in a 40% increase in conversions and a 60% improvement in page load speeds. The new platform features a headless architecture, seamless payment integration, and a mobile-first design approach.', 'RetailTech Inc.', '2023-11-15', 'React, Node.js, PostgreSQL, Tailwind CSS', 'https://example-ecommerce.com', 'https://github.com/example/ecommerce', 'active', 'Web Development', 1, true, 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=1200', '[]', 'ecommerce-platform-redesign'),

('Fintech Analytics Dashboard', 'Real-time financial data visualization and reporting dashboard.', 'Developed a comprehensive analytics dashboard for a fintech startup. The platform processes thousands of transactions per second and visualizes complex financial data through interactive, customizable charts.', 'DataFinance Corp.', '2024-02-10', 'Vue.js, Python, D3.js, AWS', 'https://example-fintech.com', '', 'active', 'Web Development', 2, false, 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200', '[]', 'fintech-analytics-dashboard'),

('Brand Identity for Tech Startup', 'Complete brand identity design including logo, typography, and visual guidelines.', 'Created a cohesive and modern brand identity for an AI-focused startup. The project included logo design, color palette selection, typography guidelines, and brand application across digital and print mediums.', 'Nexus AI', '2023-09-05', 'Adobe Illustrator, Figma', '', '', 'active', 'Branding', 3, true, 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&q=80&w=1200', '[]', 'brand-identity-nexus-ai'),

('Social Media Campaign 2024', 'Comprehensive digital marketing campaign for product launch.', 'Executed a multi-channel digital marketing campaign resulting in 2M+ impressions and a 150% ROI. The campaign leveraged influencer partnerships, targeted social ads, and content marketing.', 'StyleBrand', '2024-01-20', 'Meta Ads, Google Analytics, Hootsuite', '', '', 'active', 'Digital Marketing', 4, false, 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&q=80&w=1200', '[]', 'social-media-campaign-2024'),

('Modern Corporate Profile', 'Clean and professional graphic design for corporate profile and brochures.', 'Designed a 40-page corporate profile document that effectively communicates the company''s mission, services, and achievements with clean layouts and custom infographics.', 'Global Solutions Group', '2023-07-12', 'Adobe InDesign, Photoshop', '', '', 'active', 'Graphic Design', 5, false, 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?auto=format&fit=crop&q=80&w=1200', '[]', 'modern-corporate-profile'),

('Sustainable Fashion App', 'Mobile-first web application for a sustainable fashion brand.', 'Built a progressive web app (PWA) for a sustainable fashion brand, allowing users to track the environmental impact of their purchases and shop ethically sourced clothing.', 'EcoWear', '2024-04-01', 'Next.js, TypeScript, Supabase', 'https://example-ecowear.com', 'https://github.com/example/ecowear', 'active', 'Web Development', 6, true, 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&q=80&w=1200', '[]', 'sustainable-fashion-app');
